#ifndef __RT_AI_DRIVE_INT_MODEL_H
#define __RT_AI_DRIVE_INT_MODEL_H

#include <drive_int.h>
#include <drive_int_data.h>

/* model info ... */

// model name
#define RT_AI_DRIVE_INT_MODEL_NAME			"drive_int"
#define RT_AI_DRIVE_INT_WORK_BUFFER_BYTES		AI_DRIVE_INT_DATA_ACTIVATIONS_SIZE
#define RT_AI_DRIVE_INT_DATA_WEIGHTS_SIZE		AI_DRIVE_INT_DATA_WEIGHTS_SIZE

#define RT_AI_DRIVE_INT_BUFFER_ALIGNMENT		AI_DRIVE_INT_ACTIVATIONS_ALIGNMENT

#define RT_AI_DRIVE_INT_IN_NUM				AI_DRIVE_INT_IN_NUM
#define RT_AI_DRIVE_INT_IN_1_SIZE				AI_DRIVE_INT_IN_1_SIZE
#define RT_AI_DRIVE_INT_IN_1_SIZE_BYTES		AI_DRIVE_INT_IN_1_SIZE_BYTES
#define RT_AI_DRIVE_INT_IN_TOTAL_SIZE_BYTES	(AI_DRIVE_INT_IN_1_SIZE_BYTES)
#define RT_AI_DRIVE_INT_IN_SIZE_BYTES			{AI_DRIVE_INT_IN_1_SIZE_BYTES}


#define RT_AI_DRIVE_INT_OUT_NUM				AI_DRIVE_INT_OUT_NUM
#define RT_AI_DRIVE_INT_OUT_1_SIZE			AI_DRIVE_INT_OUT_1_SIZE
#define RT_AI_DRIVE_INT_OUT_1_SIZE_BYTES		AI_DRIVE_INT_OUT_1_SIZE_BYTES
#define RT_AI_DRIVE_INT_OUT_TOTAL_SIZE_BYTES	(AI_DRIVE_INT_OUT_1_SIZE_BYTES)
#define RT_AI_DRIVE_INT_OUT_SIZE_BYTES		{AI_DRIVE_INT_OUT_1_SIZE_BYTES}


#define RT_AI_DRIVE_INT_TOTAL_BUFFER_SIZE		(NULL)		//unused

#endif	//end
